---
- name: Install MongoDB for Packer
  hosts: default
  become: true
  
  tasks:
  - name: Install https packages
    apt:
      name: "{{ item }}"
      update_cache: yes
    loop:
      - apt-transport-https
      - ca-certificates
  - name: Import MongoDB public GPG Key
    apt_key:
      url: https://www.mongodb.org/static/pgp/server-4.2.asc
  - name: Add MongoDB source
    lineinfile:
      line: "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.2 multiverse"
      path: /etc/apt/sources.list.d/mongodb-org-4.2.list
      create: yes
  - name: Install MongoDB package
    apt:
      name: mongodb-org
      update_cache: yes
  - name: Start and enable MongoDB
    systemd:
      name: mongod.service
      state: started
      enabled: yes
