plugin: yc_compute
folders:  # List inventory hosts from these folders.
  - b1gf67o53kg106nnl0fl
filters:
#  - status == 'RUNNING'
auth_kind: serviceaccountfile
service_account_file: ../terraform/terraform-service-key.json
hostnames:
  - "{{name}}"  # Use FQDN for inventory hostnames.
# You can also format hostnames with jinja2 expressions like this
# - "{{id}}_{{name}}"

compose:
  # Set ansible_host to the Public IP address to connect to the host.
  # For Private IP use "network_interfaces[0].primary_v4_address.address".
  ansible_host: network_interfaces[0].primary_v4_address.one_to_one_nat.address

keyed_groups:
  # Place hosts in groups named by folder_id.
  - key: folder_id
    prefix: ''
    separator: ''
  - key: boot_disk['disk_id']
    prefix: ''
    separator: ''
  # Place hosts in groups named by value of labels['group'].
  - key: labels['group']
    prefix: 'otus'
    separator: '_'

groups:
  # Place hosts in 'ssd' group if they have appropriate disk_type label.
  # ssd: labels['disk_type'] == 'ssd'
